name: fomms-workshop
channels:
  - conda-forge
  - bioconda
dependencies:
  - mbuild
  - foyer
  - mdtraj
  - nglview
  - hoomd
  - mosdef_cassandra
  - cassandra
  - gromacs
  - py3dmol
  - matplotlib
  - panedr
  - signac
  - signac-flow 
  - signac-dashboard
  - pandas
  - numpy
  - h5py
  - gsd
  - openbabel
  - unyt <= 2.8
  - pip
  - pip:
    - "--editable=git+https://github.com/mosdef-hub/gmso.git@develop#egg=gmso"
    - "--editable=git+https://github.com/mosdef-hub/forcefield-utilities.git#egg=forcefield_utilities"
